<a href="https://colab.research.google.com/github/Ganesh9100/Raj9100/blob/master/image_representation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from PIL import Image
import numpy as np


In [0]:
i = Image.open('a.jpeg')
iar = np.asarray(i)
print(iar)
print(iar.shape[1])

[[[ 21  19  22]
  [ 17  15  16]
  [ 11   9  10]
  ...
  [ 75  65  56]
  [ 75  65  56]
  [ 74  64  55]]

 [[ 21  19  22]
  [ 17  15  16]
  [ 11   9  10]
  ...
  [ 75  65  56]
  [ 75  65  56]
  [ 74  64  55]]

 [[ 21  19  22]
  [ 17  15  18]
  [ 12  10  11]
  ...
  [ 75  65  56]
  [ 75  65  56]
  [ 74  64  55]]

 ...

 [[130 123 130]
  [150 143 150]
  [165 158 165]
  ...
  [196 193 202]
  [196 193 202]
  [196 193 202]]

 [[152 145 152]
  [177 170 177]
  [193 186 193]
  ...
  [196 193 202]
  [196 193 202]
  [196 193 202]]

 [[174 167 174]
  [196 189 196]
  [204 197 204]
  ...
  [196 193 202]
  [196 193 202]
  [196 193 202]]]
300


In [0]:
v=iar.reshape(iar.shape[0]*iar.shape[1]*iar.shape[2],1) #image to vector step 

print(iar.shape[0]) # restlt is dimension so 168
print(iar.shape[1])  # result in dimension 300
print(iar.shape[2])      # no of channel 3-rbg colour image 2- black and white image 




168
300
3


In [0]:
print(v) # sot its dimension is 2592 * 1936 * 3 . so 151200 rows will be there and 1 column 

[[ 21]
 [ 19]
 [ 22]
 ...
 [196]
 [193]
 [202]]
