<a href="https://colab.research.google.com/github/Ganesh9100/Raj9100/blob/master/numpy_full_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 

a=[1,2,3]
print(a)

[1, 2, 3]


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
print(mat)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
q=np.array(mat)
print(q)
print(q.shape)
print(q[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [18]:
w=np.arange(0,9)
print(w)
print()
w.reshape(3,3)

[0 1 2 3 4 5 6 7 8]



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones((6,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.random.rand(2)

array([0.86174762, 0.90793553])

In [40]:
np.random.rand(3,3)

array([[0.17181665, 0.67385242, 0.24193513],
       [0.16012943, 0.59405158, 0.7517774 ],
       [0.89244862, 0.35842388, 0.92864953]])

In [42]:
np.random.randint(2,3)  # Return random integers from low (inclusive) to high (exclusive).

2

In [43]:
np.random.randint(0,10)

7

In [46]:
q=np.ones((5,5))
print(q)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
q.reshape(1,25)  # row vector

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
q.reshape(25,1).shape

(25, 1)

In [50]:
a=q.min()
b=q.max()

print(a,b)

1.0 1.0


In [56]:
b=np.arange(0,20)
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
b.shape

(20,)

In [0]:
arr = np.arange(0,11)

In [64]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [67]:
s=arr[0:6]
print(s)

[0 1 2 3 4 5]


In [0]:
s[:]=99

In [69]:
print(s)

[99 99 99 99 99 99]


In [70]:
ar=s.copy()
print(ar)

[99 99 99 99 99 99]


In [71]:
cc=np.arange(0,26)
print(cc)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


In [0]:
cc[0:11]=45

In [75]:
print(cc)

[45 45 45 45 45 45 45 45 45 45 45 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


In [76]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
arr_2d[0:2,0:2]      #Indexing row


array([[ 5, 10],
       [20, 25]])

In [78]:

# Getting individual element value
arr_2d[1,0] # 1st row and 0th column 


20

In [89]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [91]:
arr_2d[:,1:2] # middle row 


array([[10],
       [25],
       [40]])

In [94]:
arr2d = np.zeros((10,15))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
#Length of array
arr2d.shape[1]


15

In [97]:

Y = np.array([[2, 1], [1, 2]]) 
Y


array([[2, 1],
       [1, 2]])

In [98]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [99]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [100]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [101]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix Y or X, as shown in the following figure.

In [102]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [103]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [105]:
z=X*Y
z

array([[2, 0],
       [0, 2]])

In [107]:


C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [109]:
C.T  # transpose

array([[1, 2, 3],
       [1, 2, 3]])

In [114]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A.shape

(2, 3)

In [113]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B.shape

(3, 2)

In [115]:
# Calculate the dot product

Z = np.dot(A,B)
Z
z.shape

(2, 2)